config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  root "home#index"
  get "/navigations", to: "navigations#index"

  resources :events do
    get "participants", on: :member
    member do
      post "join_event"
      delete "leave_event"
    end
  end

  resources :organizers, only: [:index]
  get "organizers/:organizer_id/events", to: "events#by_organizer", as: "organizer_events"
  resources :users, only: %i[show edit update]

  resources :participants, only: [:index]

  get "/categories", to: "categories#index"
  get "/comments", to: "comments#index"
  get "/locations", to: "locations#index"
  get "/schedules", to: "schedules#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :event
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :organizer
  has_one :location
  has_one :category
  has_many :participants, dependent: :destroy
  has_one :schedule, dependent: :destroy
  accepts_nested_attributes_for :schedule, allow_destroy: true

  def create_related_resources(event_params, current_user)
    ActiveRecord::Base.transaction do
      organizer = Organizer.find_by(user_id: current_user.id) || Organizer.create!(user_id: current_user.id)
      update!(
        title: event_params[:title],
        description: event_params[:description],
        organizer_id: organizer.id
      )
    end
  rescue ActiveRecord::RecordInvalid, StandardError
    false
  end

  def delete_checked_ownership_event
    destroy!
  rescue StandardError
    false
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  belongs_to :event
end

app/models/organizer.rb
# frozen_string_literal: true

class Organizer < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  belongs_to :event
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  belongs_to :event
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # ===== devise =====
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # ===== devise =====

  has_many :organizers
  has_many :events, through: :organizers
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def index; end

  def render_404
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def organizer?(event, user)
    event&.organizer&.user_id == user.id
  end
  helper_method :organizer?

  def participant_registered?(event, user)
    Participant.find_by(event_id: event.id, user_id: user.id).present?
  end
  helper_method :participant_registered?
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_all_events, only: %i[index show by_organizer]
  before_action :set_event, only: %i[show edit update destroy participants]
  before_action :check_owner, only: %i[edit update destroy]

  def index; end

  def show; end

  def new
    @event = Event.new
    @event.build_schedule
  end

  def create
    @event = Event.new
    if @event.create_related_resources(event_params, current_user)
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new, alert: "Failed to create event."
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @event.delete_checked_ownership_event
      redirect_to events_path, notice: "Event was successfully destroyed."
    else
      redirect_to @event, alert: "You are not allowed to delete this event."
    end
  end

  def by_organizer
    render :index
  end

  def participants
    @participants = @event.participants.page(params[:page])
    render "participants/index"
  end

  def join_event
    event = Event.find(params[:id])
    if !participant_registered?(event, current_user)
      participant = event.participants.new(user_id: current_user.id)
      if participant.save
        flash[:notice] = "Successfully joined the event."
      else
        flash[:alert] = "Failed to join the event."
      end
    else
      flash[:alert] = "You are already registered for this event."
    end
    redirect_to event_path(event)
  end

  def leave_event
    event = Event.find(params[:id])
    participant = Participant.find_by(event_id: event.id, user_id: current_user.id)
    if participant
      participant.destroy
      flash[:notice] = "Successfully left the event."
    else
      flash[:alert] = "You are not registered for this event."
    end
    redirect_to event_path(event)
  end

  private

  def set_all_events
    @organizers = Organizer.all
    if params[:organizer_id]
      organizer = Organizer.find(params[:organizer_id])
      @events = organizer.events.page(params[:page])
    else
      @events = Event.all.page(params[:page])
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def check_owner
    redirect_to @event, alert: "You are not authorized." unless @event.organizer.user_id == current_user.id
  end

  def event_params
    params.require(:event).permit(:title, :description, schedule_attributes: %i[start_time end_time])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  def index; end
end

app/controllers/organizers_controller.rb
# frozen_string_literal: true

class OrganizersController < ApplicationController
  before_action :set_all_events, only: %i[index]

  def index; end

  private

  def set_all_events
    @organizers ||= Organizer.page(params[:page])
  end
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  before_action :set_event

  def index
    @participants = @event.participants
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :authorize_user, only: %i[show edit update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, alert: "Failed to update user."
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    render_404 unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categorys/index.html.erb
<h1>categories</h1>

app/views/comments/index.html.erb
<h1>Comments</h1>

app/views/events/_filter.html.erb
<div class="relative inline-flex mt-4 m-4">
  <svg class="w-2 h-2 absolute top-0 right-0 m-4 pointer-events-none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 412 232"><path d="M206 171.144L42.678 7.822c-9.763-9.763-25.592-9.763-35.355 0C-2.792 17.923-2.792 37.271 7.323 47.336L175.637 215.67c9.763 9.763 25.592 9.763 35.355 0l168.314-168.314c9.765-9.764 9.765-25.592 0-35.355-9.763-9.763-25.592-9.763-35.355 0L206 171.144z" fill="#648299" fill-rule="nonzero"/></svg>
  <select onchange="location = this.value;" class="border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none">
    <option value="">Filter by organizer</option>
    <% @organizers.each do |organizer| %>
      <option value="<%= organizer_events_path(organizer) %>"><%= organizer.user.name %></option>
    <% end %>
  </select>
</div>

app/views/events/edit.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
  <div class="card bordered">
    <div class="card-body">
      <h2 class="card-title text-center">Update Event</h2>
      <%= form_for @event do |f| %>
        <div class="form-control">
          <label class="label"> <span class="label-text">Event Title</span> </label>
          <%= f.text_field :title, class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <label class="label"> <span class="label-text">Event Description</span> </label>
          <%= f.text_area :description, class: "textarea textarea-bordered" %>
        </div>
        <%= f.fields_for :schedule do |s| %>
          <div class="form-control">
            <label class="label"> <span class="label-text">Start Time</span> </label>
            <%= s.datetime_field :start_time, class: "input input-bordered" %>
          </div>
          <div class="form-control">
            <label class="label"> <span class="label-text">End Time</span> </label>
            <%= s.datetime_field :end_time, class: "input input-bordered" %>
          </div>
        <% end %>
        <%= f.submit "Update Event", class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= render "filter" %>

<div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-4">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 p-4">
    <% @events.each do |event| %>
      <div class="card bordered">
        <div class="card-body">
          <h2 class="card-title text-center"><%= event.title %></h2>
          <p><%= event.description %></p>
          <p>Created at: <%= event.created_at.strftime('%Y-%m-%d %H:%M') %></p>
          <%= link_to "View Event", event_path(event), class: "btn btn-primary mt-4" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= paginate @events %>

app/views/events/new.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
  <div class="card bordered">
    <div class="card-body">
      <h2 class="card-title text-center">Create Event</h2>
      <%= form_for @event do |f| %>
        <div class="form-control">
          <label class="label"> <span class="label-text">Event Title</span> </label>
          <%= f.text_field :title, class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <label class="label"> <span class="label-text">Event Description</span> </label>
          <%= f.text_area :description, class: "textarea textarea-bordered" %>
        </div>
        <div class="form-control">
          <label class="label"> <span class="label-text">Event Date</span> </label>
          <%= f.fields_for :schedule do |s| %>
            <div class="form-control">
              <label class="label"> <span class="label-text">Start Time</span> </label>
              <%= s.datetime_field :start_time, class: "input input-bordered" %>
            </div>
            <div class="form-control">
              <label class="label"> <span class="label-text">End Time</span> </label>
              <%= s.datetime_field :end_time, class: "input input-bordered" %>
            </div>
          <% end %>
        </div>
        <%= f.submit "Create Event", class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="card bordered p-4">
  <div class="card-body">
    <h2 class="card-title text-3xl font-bold mb-4"><%= @event.title %></h2>
    <p class="text-gray-500 text-lg mb-4"><%= @event.description %></p>
    <p class="text-gray-500 mb-2"><strong>Organized by:</strong> <%= @event&.organizer&.user&.name %></p>
    <p class="text-gray-500 mb-2"><strong>Location:</strong> <%= @event&.location&.location %></p>
    <p class="text-gray-500 mb-2"><strong>Category:</strong> <%= @event&.category&.category %></p>
    <p class="text-gray-500 mb-2"><strong>Created at:</strong> <%= @event.created_at.strftime("%B %d, %Y %H:%M") %></p>
    <p class="text-gray-500 mb-2"><strong>Updated at:</strong> <%= @event.updated_at.strftime("%B %d, %Y %H:%M") %></p>

    <div class="flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-2 mt-4">
      <%= link_to "Back to Events", events_path, class: "btn btn-primary" %>
      <%= link_to "Share Event", event_path(@event, format: :json), class: "btn btn-primary mr-2" %>
      <%= link_to "Participant List", participants_event_path(@event), class: "btn btn-primary mr-2" %>
      <% if organizer?(@event, current_user) %>
        <%= link_to "Edit Event", edit_event_path(@event), class: "btn btn-accent mr-2" %>
        <%= button_to "Destroy", event_path(@event), method: :delete, data: { turbo: false, turbo_confirm: "Are you sure?" }, class: "btn btn-secondary mr-2" %>
      <% elsif participant_registered?(@event, current_user) %>
        <%= button_to "Leave Event", leave_event_event_path(@event), method: :delete, data: { turbo: false, turbo_confirm: "Are you sure?" }, class: "btn btn-secondary mr-2" %>
      <% else %>
        <%= button_to 'Join Event', join_event_event_path(@event), form: { data: { turbo_method: "post", turbo_confirm: "Are you sure you want to join this event?" } }, class: "btn btn-accent mr-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%# https://daisyui.com/components/hero/#centered-hero %>

<div class="hero min-h-screen">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold">Hello there</h1>
      <p class="py-6">Efficiently manage your events with this service, offering real-time attendee tracking, QR code check-ins, and easy event detail sharing.</p>
      <%= link_to "Get Started", navigations_path, method: :get, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/navigations/index.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
  <div class="card bordered">
    <div class="card-body">
      <h2 class="card-title text-3xl font-bold">Create Event</h2>
      <p class="text-gray-500">Create and manage your own events.</p>
      <%= link_to "Create Event", new_event_path, method: :get, class: "btn btn-primary mt-4" %>
    </div>
  </div>

  <div class="card bordered">
    <div class="card-body">
      <h2 class="card-title text-3xl font-bold">View and Join Events</h2>
      <p class="text-gray-500">Browse existing events and join the ones you're interested in.</p>
      <%= link_to "View Events", events_path, method: :get, class: "btn btn-primary mt-4" %>
    </div>
  </div>
</div>

app/views/organizers/index.html.erb
<div class="overflow-x-auto m-4">
  <table class="table w-full">
    <thead>
      <tr>
        <th>
          <label>
            <input type="checkbox" class="checkbox" />
          </label>
        </th>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @organizers.each do |organizer| %>
        <tr>
          <th>
            <label>
              <input type="checkbox" class="checkbox" />
            </label>
          </th>
          <td>
            <div class="flex items-center space-x-3">
              <div>
                <div class="font-bold"><%= organizer.user&.name %></div>
                <div class="text-sm opacity-50"><%= organizer.user&.email %></div>
              </div>
            </div>
          </td>
          <td>
            Organizer
            <br/>
            <span class="badge badge-ghost badge-sm">Role</span>
          </td>
          <td>
            <%= link_to 'details', organizer_events_path(organizer), class: "btn btn-ghost btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @organizers %>
</div>

app/views/participants/index.html.erb
<div class="overflow-x-auto m-4">
  <table class="table w-full">
    <thead>
      <tr>
        <th>
          <label>
            <input type="checkbox" class="checkbox" />
          </label>
        </th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <th>
            <label>
              <input type="checkbox" class="checkbox" />
            </label>
          </th>
          <td>
            <div class="flex items-center space-x-3">
              <div>
                <% user = User.find(participant.user_id) %>
                <div class="font-bold"><%= user&.name %></div>
                <div class="text-sm opacity-50"><%= user.email %></div>
              </div>
            </div>
          </td>
          <td>
            Participant
            <br/>
            <span class="badge badge-ghost badge-sm">Role</span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/schedules/_flash.html.erb
<%# https://daisyui.com/components/alert/#info-color %>
<%# https://daisyui.com/components/alert/#error-color %>

<% if flash.present? %>
  <% flash.each do |type, message| %>
    <% if type == "notice" %>
      <p class="notice">
        <div class="alert alert-info">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          <span><%= notice %></span>
        </div>
      </p>
    <% else %>
      <p class="alert">
        <div class="alert alert-error">
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span><%= alert %></span>
        </div>
      </p>
  <% end %>
<% end %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

app/views/users/edit.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
  <div class="card bordered">
    <div class="card-body">
      <h2 class="card-title text-center">Update User</h2>
      <%= form_for @user do |f| %>
        <div class="form-control">
          <label class="label"> <span class="label-text">User Name</span> </label>
          <%= f.text_field :name, class: "input input-bordered" %>
        </div>
        <div class="form-control">
          <label class="label"> <span class="label-text">User Email</span> </label>
          <%= f.text_field :email, class: "input input-bordered" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-primary mt-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card bordered p-4">
  <div class="card-body">
    <h2 class="card-title text-3xl font-bold mb-4"><%= @user&.name %></h2>
    <p class="text-gray-500 text-lg mb-4"><%= @user.email %></p>

    <div class="flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-2 mt-4">
      <%= link_to "Edit User", edit_user_path(@user), class: "btn btn-accent mr-2" %>
    </div>
  </div>
</div>