config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  root "home#index"
  get "/navigations", to: "navigations#index"

  resources :events do
    get "participants", on: :member
    member do
      post "join_event"
      delete "leave_event"
    end
  end

  resources :organizers, only: [:index]
  get "organizers/:organizer_id/events", to: "events#by_organizer", as: "organizer_events"
  resources :users, only: %i[show edit update]

  resources :participants, only: [:index]

  get "/categories", to: "categories#index"
  get "/comments", to: "comments#index"
  get "/locations", to: "locations#index"
  get "/schedules", to: "schedules#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :event
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :organizer
  has_one :location
  has_one :category
  has_many :participants, dependent: :destroy
  has_one :schedule, dependent: :destroy
  accepts_nested_attributes_for :schedule, allow_destroy: true

  def create_related_resources(event_params, current_user)
    ActiveRecord::Base.transaction do
      organizer = Organizer.find_by(user_id: current_user.id) || Organizer.create!(user_id: current_user.id)
      update!(
        title: event_params[:title],
        description: event_params[:description],
        organizer_id: organizer.id
      )
    end
  rescue ActiveRecord::RecordInvalid, StandardError
    false
  end

  def delete_checked_ownership_event
    destroy!
  rescue StandardError
    false
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  belongs_to :event
end

app/models/organizer.rb
# frozen_string_literal: true

class Organizer < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  belongs_to :event
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  belongs_to :event
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # ===== devise =====
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # ===== devise =====

  has_many :organizers
  has_many :events, through: :organizers
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def index; end

  def render_404
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def organizer?(event, user)
    event&.organizer&.user_id == user.id
  end
  helper_method :organizer?

  def participant_registered?(event, user)
    Participant.find_by(event_id: event.id, user_id: user.id).present?
  end
  helper_method :participant_registered?
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_all_events, only: %i[index show by_organizer]
  before_action :set_event, only: %i[show edit update destroy participants]
  before_action :check_owner, only: %i[edit update destroy]

  def index; end

  def show; end

  def new
    @event = Event.new
    @event.build_schedule
  end

  def create
    @event = Event.new
    if @event.create_related_resources(event_params, current_user)
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new, alert: "Failed to create event."
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @event.delete_checked_ownership_event
      redirect_to events_path, notice: "Event was successfully destroyed."
    else
      redirect_to @event, alert: "You are not allowed to delete this event."
    end
  end

  def by_organizer
    render :index
  end

  def participants
    @participants = @event.participants.page(params[:page])
    render "participants/index"
  end

  def join_event
    event = Event.find(params[:id])
    if !participant_registered?(event, current_user)
      participant = event.participants.new(user_id: current_user.id)
      if participant.save
        flash[:notice] = "Successfully joined the event."
      else
        flash[:alert] = "Failed to join the event."
      end
    else
      flash[:alert] = "You are already registered for this event."
    end
    redirect_to event_path(event)
  end

  def leave_event
    event = Event.find(params[:id])
    participant = Participant.find_by(event_id: event.id, user_id: current_user.id)
    if participant
      participant.destroy
      flash[:notice] = "Successfully left the event."
    else
      flash[:alert] = "You are not registered for this event."
    end
    redirect_to event_path(event)
  end

  private

  def set_all_events
    @organizers = Organizer.all
    if params[:organizer_id]
      organizer = Organizer.find(params[:organizer_id])
      @events = organizer.events.page(params[:page])
    else
      @events = Event.all.page(params[:page])
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def check_owner
    redirect_to @event, alert: "You are not authorized." unless @event.organizer.user_id == current_user.id
  end

  def event_params
    params.require(:event).permit(:title, :description, schedule_attributes: %i[start_time end_time])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  def index; end
end

app/controllers/organizers_controller.rb
# frozen_string_literal: true

class OrganizersController < ApplicationController
  before_action :set_all_events, only: %i[index]

  def index; end

  private

  def set_all_events
    @organizers ||= Organizer.page(params[:page])
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :authorize_user, only: %i[show edit update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, alert: "Failed to update user."
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    render_404 unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/common/_flash.html.erb
<%# https://daisyui.com/components/alert/#info-color %>
<%# https://daisyui.com/components/alert/#error-color %>

<% if notice %>
  <p class="notice"><span><%= notice %></span></p>
<% elsif alert %>
  <p class="alert"><span><%= alert %></span></p>
<% end %>

app/views/common/_footer.html.erb
<%# https://daisyui.com/components/footer/#centered-footer-with-social-icons %>

<footer class="footer footer-center p-10 bg-base-200 text-base-content rounded">
  <div class="grid grid-flow-col gap-4">
    <a class="link link-hover">About us</a> 
    <a class="link link-hover">Contact</a> 
    <a class="link link-hover">Jobs</a> 
    <a class="link link-hover">Press kit</a>
  </div> 
  <div>
    <p>Copyright © 2023 - All right reserved by ACME Industries Ltd</p>
  </div>
</footer>

app/views/common/_header.html.erb
<%# https://daisyui.com/components/navbar/ %>
<%# https://daisyui.com/components/navbar/#navbar-with-dropdown-center-logo-and-icon %>

<div class="navbar bg-base-100">
  <div class="navbar-start">
    <% if user_signed_in? %>
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost btn-circle">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
        </label>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
          <li><%= link_to "Top", root_path %>
          <li><%= link_to "Events", navigations_path %>
          <li><%= link_to "Organizers", organizers_path %>
          <li><%= link_to "MyPage", user_path(current_user) %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %></li>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="navbar-center">
    <%= link_to "Event Participant Manager Web", navigations_path, class: "btn btn-ghost normal-case text-sm sm:text-3xl whitespace-nowrap overflow-hidden overflow-ellipsis" %>
  </div>
  <div class="navbar-end">
    <% if user_signed_in? %>
      <button class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
      </button>
      <button class="btn btn-ghost btn-circle">
        <div class="indicator">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
          <span class="badge badge-xs badge-primary indicator-item"></span>
        </div>
      </button>
    <% end %>
  </div>
</div>